/*
=============================================================
This is the learning journey of 'Filter' Topic 
** All of them are used in [WHERE] condtion, with aim to filter data **
=============================================================

< Used Database >:  
    (1) MyDatabase
        >> File Path: datasets/init-sqlserver-mydatabase.sql


< Contents Involved >: 
    
    >> Comparison Operators:
        (1) Equal: =
        (2) Not Equal: <> !=
        (3) Greater & Smaller: > & <
        (4) Greater or Equal to & Smaller or Equal to: >= & <=
    
    >> Logical Operators:
        (3) AND:        All conditions must be TRUE
        (4) OR:         At least one condition must be TRUE
        (5) NOT:        Excludes matching values
    
    >> Range Operators:
        (6) BETWEEN:    Check if a value is within a range (Boundary inclusive)

    >> Membership Operators:
        (7) IN:         Check if a value exists in a list
        (8) NOT IN:     Check if a value NOT exists in a list 
    
    >> Search Operators:
        (9) LIKE:       Search for a pattern in text ('%' stands for anything, '_' stands for 1 letter)

< Note >:
    (1) LIKE: ignore uppercase & lowercase

=============================================================
This document was generated by Yulin Zhou on 2025/05/01
=============================================================
*/

USE MyDatabase;

-- ======================================================
-- Comparison Operators
-- ======================================================

-- Retrieve all customers from Germany
SELECT *
FROM customers
WHERE country = 'Germany';


-- Retrieve all customers who are NOT from Germany
SELECT *
FROM customers
WHERE country != 'Germany';



-- ======================================================
-- Logical Operators
-- ======================================================

-- Retrieve all customers who are from USA and have a score greater than 500
SELECT 
    *
FROM
    customers
WHERE
    country = 'USA' AND score > 500;
    

-- Retrieve all customers with a score not less than 500
SELECT * 
FROM customers
WHERE NOT score < 500;


-- ======================================================
-- Range Operators
    -- >> Between (Check if a value is within a range, boundary inclusive)
-- ======================================================

-- Retrieve all customers whose score falls in the range between 100 and 500
SELECT *
FROM customers
WHERE score BETWEEN 100 AND 500; -- the value should range from the smaller to the larger (cannot be reversed)

SELECT *
FROM customers
WHERE score >= 100 AND score <= 500;



-- ======================================================
-- Membership Operators: Check if a value exists in a list ot Not
-- ======================================================


-- Retrieve all customers from either Germany or USA
SELECT *
FROM customers
WHERE country IN ('Germany', 'USA');



-- ======================================================
-- Search Operators: Like (ignore uppercase & lowercase)
    -- >> '%': Anything (0 or 1 or many); 
    -- >> '_': Exact 1;
-- ======================================================


-- Find all customers whose first name starts with 'M'
SELECT *
FROM customers
WHERE first_name LIKE 'M%'; -- also can use 'm%'


-- Find all customers whose first name ends with 'n'
SELECT *
FROM customers
WHERE first_name LIKE '%n';  -- also can use '%N'


-- Find all customers whose first name contains 'r'
SELECT *
FROM customers
WHERE first_name LIKE '%r%'; -- also can use '%R%'


-- Find all customers whose first name has 'r' in the third place
SELECT *
FROM customers
WHERE first_name LIKE '__r%';
